search_terms = [
    "A Lange Sohne",
    "Alain Silberstein",
    "Bell & Ross",
    "Bethune",
    "Blancpain",
    "Bovet",
    "Breguet",
    "Bremont",
    "Cartier",
    "Chopard",
    "Chronoswiss",
    "Concord",
    "Corum",
    "Dubey Schaldenbrand",
    "Eberhard",
    "Franck Muller",
    "Gerald Genta",
    "Girard Perregaux",
    "Glashutte Original",
    "Grand Seiko",
    "H Moser",
    "Habring",
    "Hamilton",
    "Heuer",
    "Hublot",
    "IWC",
    "Jaeger LeCoultre",
    "Jaquet Droz",
    "Jean d'Eve",
    "Jeanrichard",
    "Junghans",
    "Kobold",
    "Lemania",
    "Longines",
    "Maurice Lacroix",
    "Nomos",
    "Omega",
    "Oris",
    "Parmigiani",
    "Patek",
    "Piaget",
    "Porsche Design",
    "RGM",
    "Ressence",
    "Sinn",
    "Stowa",
    "Tudor",
    "Ulysse Nardin",
    "Universal Geneve",
    "Vacheron",
    "Vulcain",
    "Zenith"
]

stop_words = {
    "none": " ",
    "general": " -homage -replica -pocket -clock -antique -vintage -vtg -new -handmade -conversion -signed -trench -lady -ladies -woman -women",
    "no_vintage": " -vintage -vtg -antique",
    "no_quartz": " -quartz -battery"
}
